In [4]:
import seaborn as sns
import matplotlib.pyplot as plt
fmri = sns.load_dataset('fmri')
fmri.head()

  subject  timepoint event    region    signal
0     s13         18  stim  parietal -0.017552
1      s5         14  stim  parietal -0.080883
2     s12         18  stim  parietal -0.081033
3     s11         18  stim  parietal -0.046134
4     s10         18  stim  parietal -0.037970

In [5]:
import seaborn as sns
import matplotlib.pyplot as plt
fmri = sns.load_dataset('fmri')
fmri.describe()

         timepoint       signal
count  1064.000000  1064.000000
mean      9.000000     0.003540
std       5.479801     0.093930
min       0.000000    -0.255486
25%       4.000000    -0.046070
50%       9.000000    -0.013653
75%      14.000000     0.024293
max      18.000000     0.564985